export const SET_PAGE_DATA = "SET_PAGE_DATA";
export const SET_ART_DATA = "SET_ART_DATA";
export const FILTER_ART = "FILTER_ART";
export const SET_FAVORITE = "SET_FAVORITE";
export const UNSET_FAVORITE = "UNSET_FAVORITE";
export const SET_FAVORITES_LOCAL_STORAGE = "SET_FAVORITES_LOCAL_STORAGE";
